### ISSUE TITLE
too many commits 🤓 

### ISSUE THREAD

**Issue by tuetenk0pp** [antonbrall/permanent-web-snapshots#1]

**Comment by antonbrall** [comment]
G̸̝͍͍̬͈̺͚̑̈̔͊̐̈́̄̏̌̀̒͗̉́͑̒̔͐͑́į̸̢̡̢̧̹̩̦̗̼̤̬̤̙͖͍̱̻̺̗̖̫͙̟̻͎͖̥̩̩͍͇͍̞̺̓̽̽͐̅̊̽͑̃̈̃̓͠t̶̢̡̢̛̫̲̰̹̹̖̮̱̗̠̲̙̖̮͎̲̝͙͍̯͔̙̜̝̭̱͔͈̪̝͈͓̪̪̲̣̀̽̌̑̏̈́̍͛̎̋̌̈́͌̃͋̾̽͆͋̏̕͝͠ͅḩ̸̯͙̺̞͉̠̟̰̙͙̲̠̱̖͗̐̓̐͐́̑͛̏̑̑̕͜͜͝͠ͅư̶̡̧̳̥̙͔̱͋̇̏̂̌͛͂̀̿̃͌̔̚͝͝b̵̡̡̞̗̤̬̠͖̦͔͉̰̦̯̩̫̤͌̈́͐̐͑͝ ̶̣͍̰̥̋́̂͊̽̓͂̑̾͋̅̅̀́̾̂̈́͘Ą̵̡͖̟̠̗̠̰̰͚̘̪̯̻̟̱͓̤̭͔̪̰̹̬͉̱̣͎̝̞̳͔̺͖̑̇̈͛̿͊͐̕͜͠ͅć̴̣̔̊̂͂̀̿̐͗̈́̓̄̌͠t̵̨̧̜͓̹̯̬̬̠̖̺̼̖͕̱̞̝͕̩͍͖̮̱̭͓͙͔͍̔͊̔͗͐̐̍̆̏̐́̄̀̅̄͌̽͗̊̂̊̋͗̽͘̕͘͘̚͜͜i̸̡̨̨͚̲̹̘͖̙͇̱̳̼̳̣̙̪̤̙͈̰͎͕͎̠͕̙͕͈͕̞̝̙̼̲̱̭͛͑̿̽̽́͗̃̌̀̅̓̑̃̕͘͜͝͠͝͝͠ͅȯ̵̢̢͔̳̠̭̣͍͙̥͇̱̻̉́̾̎͆̾́̅̔͊̐̄̀̊̀̏́̑͌̌̐͐͠͝͝n̶̨̨̧̳͔̮̳̪̟͕̼͖̟͙͉̪̳̼͔̮̗̯̬͔͍͈͈̦͇͈̒̈́̅̾̑̀̆̔͛̈́̉̏͌̓͒̀̈́̊̂͊̀͌̕͠ͅș̸͎̘̼͚̩̼̟͔̜̏̿̽̽͜͜͝    🤷

**Comment by antonbrall** [comment]
G̸̝͍͍̬͈̺͚̑̈̔͊̐̈́̄̏̌̀̒͗̉́͑̒̔͐͑́į̸̢̡̢̧̹̩̦̗̼̤̬̤̙͖͍̱̻̺̗̖̫͙̟̻͎͖̥̩̩͍͇͍̞̺̓̽̽͐̅̊̽͑̃̈̃̓͠t̶̢̡̢̛̫̲̰̹̹̖̮̱̗̠̲̙̖̮͎̲̝͙͍̯͔̙̜̝̭̱͔͈̪̝͈͓̪̪̲̣̀̽̌̑̏̈́̍͛̎̋̌̈́͌̃͋̾̽͆͋̏̕͝͠ͅḩ̸̯͙̺̞͉̠̟̰̙͙̲̠̱̖͗̐̓̐͐́̑͛̏̑̑̕͜͜͝͠ͅư̶̡̧̳̥̙͔̱͋̇̏̂̌͛͂̀̿̃͌̔̚͝͝b̵̡̡̞̗̤̬̠͖̦͔͉̰̦̯̩̫̤͌̈́͐̐͑͝ ̶̣͍̰̥̋́̂͊̽̓͂̑̾͋̅̅̀́̾̂̈́͘Ą̵̡͖̟̠̗̠̰̰͚̘̪̯̻̟̱͓̤̭͔̪̰̹̬͉̱̣͎̝̞̳͔̺͖̑̇̈͛̿͊͐̕͜͠ͅć̴̣̔̊̂͂̀̿̐͗̈́̓̄̌͠t̵̨̧̜͓̹̯̬̬̠̖̺̼̖͕̱̞̝͕̩͍͖̮̱̭͓͙͔͍̔͊̔͗͐̐̍̆̏̐́̄̀̅̄͌̽͗̊̂̊̋͗̽͘̕͘͘̚͜͜i̸̡̨̨͚̲̹̘͖̙͇̱̳̼̳̣̙̪̤̙͈̰͎͕͎̠͕̙͕͈͕̞̝̙̼̲̱̭͛͑̿̽̽́͗̃̌̀̅̓̑̃̕͘͜͝͠͝͝͠ͅȯ̵̢̢͔̳̠̭̣͍͙̥͇̱̻̉́̾̎͆̾́̅̔͊̐̄̀̊̀̏́̑͌̌̐͐͠͝͝n̶̨̨̧̳͔̮̳̪̟͕̼͖̟͙͉̪̳̼͔̮̗̯̬͔͍͈͈̦͇͈̒̈́̅̾̑̀̆̔͛̈́̉̏͌̓͒̀̈́̊̂͊̀͌̕͠ͅș̸͎̘̼͚̩̼̟͔̜̏̿̽̽͜͜͝    🤷
